version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_BUILD_NUM .
            docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest .
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_BUILD_NUM
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
      - add_ssh_keys:
          fingerprints:
            - "SHA256:v7sQkiRxODHS2ZO8ef4V9nfdcXyn5ugj0vo8+Mhd4VY"
      - run:
          name: Deploy to EC2
          command: |
            echo $SSH_USER
            echo $SSH_HOST
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '
              docker pull '$DOCKERHUB_USERNAME'/'$DOCKERHUB_REPO':latest
              docker stop my-website || true
              docker rm my-website || true
              docker run -d --name my-website --restart unless-stopped -p 80:80 '$DOCKERHUB_USERNAME'/'$DOCKERHUB_REPO':latest
              docker image prune -f
            '

workflows:
  build-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
