version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      
      # SSH Setup using CircleCI's SSH key management
      - add_ssh_keys:
          fingerprints:
            - "SHA256:jqchFsMzc2aYy2+8SmbnvmXvnCkkAQHZOgjjpOM9g38"
      
      # Enhanced SSH Debugging
      - run:
          name: Debug SSH Connection
          command: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            echo "=== SSH Key Location ==="
            ls -la ~/.ssh/
            echo "=== Known Hosts ==="
            ssh-keyscan -v 13.201.87.22 >> ~/.ssh/known_hosts
            cat ~/.ssh/known_hosts
            echo "=== Connection Test ==="
            ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_* ec2-user@13.201.87.22 "echo 'SSH connection successful!'"
            echo "=== Key Scan ==="
            ssh-keyscan -v 13.201.87.22
      
      # Docker Setup
      - setup_remote_docker
      
      # Docker Login
      - run:
          name: Docker Login
          command: |
            docker login -u "yashwagh30" -p "Y@shdocker30"

      # Build and Push
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t yashwagh30/ecoharmony:latest .
            docker push yashwagh30/ecoharmony:latest
      
      # Deployment with PROPERLY ESCAPED HEREDOC
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_* ec2-user@13.201.87.22 \<< 'EOF'
            docker pull yashwagh30/ecoharmony:latest
            docker stop ecoharmony-container || true
            docker rm ecoharmony-container || true
            docker run -d -p 80:80 --name ecoharmony-container yashwagh30/ecoharmony:latest
            EOF

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-deploy
